export const SET_PRODUCTS = "SET_PRODUCTS";
export const OPEN_MODAL_FOR_ADD_PRODUCT_TO_CART = "OPEN_MODAL_FOR_ADD_PRODUCT_TO_CART";
export const ADD_PRODUCT_TO_FAVORITE = "ADD_PRODUCT_TO_FAVORITE";
export const OPEN_MODAL_FOR_ADD_FAVORITE_PRODUCT_TO_CART = "OPEN_MODAL_FOR_ADD_FAVORITE_PRODUCT_TO_CART";
export const DELETE_PRODUCT_FROM_FAVORITE = "DELETE_PRODUCT_FROM_FAVORITE";
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const DELETE_PRODUCT_FROM_CART = "DELETE_PRODUCT_FROM_CART";
export const CLOSE_MODAL_FOR_ADD_TO_CART = "CLOSE_MODAL_FOR_ADD_TO_CART";
export const CLOSE_MODAL_FOR_DELETE_PRODUCT_FROM_CART = "CLOSE_MODAL_FOR_DELETE_PRODUCT_FROM_CART";
export const OPEN_MODAL_FOR_DELETE_PRODUCT_FROM_CART = "OPEN_MODAL_FOR_DELETE_PRODUCT_FROM_CART";
export const FAVORITE_FROM_LOCAL_STORAGE = "FAVORITE_FROM_LOCAL_STORAGE";
export const CART_FROM_LOCAL_STORAGE = "CART_FROM_LOCAL_STORAGE";
export const TOTAL_SUM = "TOTAL_SUM";
export const SET_USER_DATA = "SET_USER_DATA";
export const SET_ORDER_DATA = "SET_ORDER_DATA";
export const CLOSE_MODAL_FINISH_USER_APPLICATION = "CLOSE_MODAL_FINISH_USER_APPLICATION";
export const CONSOLE_LOG= "CONSOLE_LOG";

